#!/bin/sh

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

if [ "$prefix" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

trap "./rem" INT TERM HUP ALARM

echo "*** PREEMPTION TEST (kernel) ***"
echo "Press <enter> to load modules:"
read junk
insmod $MODULES/rtai_hal.ko IsolCpusMask=0;
insmod $MODULES/rtai_sched.ko;
echo "Now start it <enter>."
read junk
insmod ./preempt.ko;
echo
echo "Done. Press <enter> to remove the modules. Then do 'dmesg' to see what happened"
read junk
./rem
