#!/bin/sh

libpath=`rtai-config --library-dir`

if [ "$libpath" == "" ]; then
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

export LD_LIBRARY_PATH=$libpath:$LD_LIBRARY_PATH

if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** SIMPLE RT TASK (user mode) ***"
echo "Press <enter> to load LXRT modules:"
read junk
./ldmod
echo
echo "Now start the realtime process <enter>:"
read junk
./rt_process &
TASKPID=`ps -a |grep rt_process | awk '{ print $1 }'`
sleep 10
kill -9 $TASKPID 
echo
echo "Done. Press <enter> to remove the modules."
read junk
./remod
