#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** RM SCHEDULING (kernel) ***"
echo "Press <enter> to load modules:"
read junk
./ldmod
echo
echo "Now start the realtime process <enter>, <enter> again to end it."
read junk
sync
insmod ./rm_rt.ko;
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
